BASE ?= arm-none-eabi

CC      = $(BASE)-gcc
LD      = $(BASE)-gcc
AS      = $(BASE)-as
CP      = $(BASE)-objcopy
DUMP    = $(BASE)-objdump
SIZE    = $(BASE)-size

TODAY = $(shell date +"%y%m%d")

PRJ = firmware
SRC = hw/ATSAMV71/cstartup.c hw/ATSAMV71/hardware.c hw/ATSAMV71/spi.c hw/ATSAMV71/qspi.c hw/ATSAMV71/mmc.c hw/ATSAMV71/usbdev.c  hw/ATSAMV71/eth.c hw/ATSAMV71/irq/nvic.c
SRC += hw/ATSAMV71/network/intmath.c hw/ATSAMV71/network/gmac.c hw/ATSAMV71/network/gmacd.c hw/ATSAMV71/network/phy.c hw/ATSAMV71/network/ethd.c
SRC += firmware.c fpga.c syscalls.c main.c menu.c osd.c hdd.c state.c user_io.c user_io_hid.c data_io.c idxfile.c acsi_hdc.c ini_parser.c cue_parser.c mist_cfg.c arc_file.c font.c utils.c serial_sink.c
SRC += it6613/HDMI_TX.c it6613/it6613_drv.c it6613/it6613_sys.c it6613/EDID.c it6613/hdmitx_mist.c
SRC += usb/hid.c usb/hidparser.c usb/hidquirks.c usb/joymapping.c usb/joystick.c usb/storage.c usb/asix.c usb/cdc_ecm.c usb/pl2303.c
SRC += usb/usb.c usb/max3421e.c usb/usb-max3421e.c usb/hub.c usb/usbdebug.c usb/timer.c
# SRC += usb/rtc.c usb/rtc/i2c-tiny.c usb/rtc/i2c-mcp2221.c usb/rtc/pcf85263.c usb/rtc/ds3231.c
# SRC += usb/usb-samv71.c
SRC += FatFs/ff.c FatFs/ffunicode.c
SRC += fat_compat.c diskio.c
SRC += support/minimig/core.c support/minimig/boot.c support/minimig/config.c support/minimig/fdd.c support/minimig/menu.c
SRC += support/8bit/core.c support/8bit/idx_files.c support/pcecd.c support/neocd.c support/psx.c support/snes.c support/8bit/menu.c support/8bit/menu_info.c support/8bit/settings.c
SRC += support/tos.c support/archie.c support/zx_col.c cdc_control.c storage_control.c
SRC += support/config_union.c
SRC += sxmlc/sxmlc.c

OBJ = $(SRC:.c=.o)
DEP = $(SRC:.c=.d)

LINKMAP = hw/ATSAMV71/flash.ld
LIBDIR  =

# Commandline options for each tool.
# for ESA11 add -DEMIST
DFLAGS  = -D_GNU_SOURCE -DCONFIG_HAVE_NVIC -DCONFIG_HAVE_ETH -DCONFIG_HAVE_GMAC -DCONFIG_HAVE_GMAC_QUEUES -DGMAC_QUEUE_COUNT=6 -DCONFIG_ARCH_ARM -DCONFIG_ARCH_ARMV7M -DCONFIG_CHIP_SAMV71 -DCONFIG_PACKAGE_100PIN
DFLAGS += -DCONFIG_FLASH_1024KB -DFW_ID=\"SIDIUPG\" -DSZ_TBL=2048 -DDEFAULT_CORE_NAME=\"SIDI128.RBF\" -DSD_NO_DIRECT_MODE -DJOY_DB9_MD -DHAVE_QSPI -DHAVE_HDMI -DHAVE_PSX -DHAVE_XML
DFLAGS += -DMIST -DVDATE=\"$(TODAY)\" -DUSB_STORAGE -DUSB_ASIX_NET -DUSB_PL2303_CDC -DFF_FS_TINY=0 -DFF_MAX_LFN=160 -DFF_LFN_BUF=160 -DSECTOR_BUFFER_SIZE=8192
#DFLAGS += -DPROTOTYPE
CFLAGS  = $(DFLAGS) -mcpu=cortex-m7 -mthumb -I. -Iarch -Icmsis -Iusb -Isupport -Ihw/ATSAMV71
CFLAGS += $(CFLAGS-$@) -ffunction-sections -fsigned-char -fno-common -c --std=gnu99 -O2
AFLAGS  = -ahls -mapcs-32
LFLAGS  = -mcpu=cortex-m7 -mthumb -Wl,-Map,$(PRJ).map -T$(LINKMAP) $(LIBDIR)
CPFLAGS = --output-target=ihex

MKUPG = mkupg

# Libraries.
LIBS    =

# Our target.
all: $(PRJ).hex $(PRJ).upg

clean:
	rm -f *.d *.o *.hex *.elf *.map *.lst core *~ */*.d */*.o */*/*.d */*/*.o */*/*/*.d */*/*/*.o  $(MKUPG) *.bin *.upg *.exe

INTERFACE=-f interface/ftdi/olimex-arm-usb-tiny-h.cfg -f interface/ftdi/olimex-arm-jtag-swd.cfg
#INTERFACE=interface/busblaster.cfg
#INTERFACE=openocd/interface/esa11-ft4232-generic.cfg
ADAPTER_KHZ=1800

reset:
	openocd $(INTERFACE) -f target/atsamv.cfg --command "adapter speed $(ADAPTER_KHZ); init; reset init; resume; shutdown"

debug:
	openocd $(INTERFACE) -f target/atsamv.cfg --command "adapter speed $(ADAPTER_KHZ); init; reset init; resume"

$(MKUPG): $(MKUPG).c
	gcc  -DFW_ID=\"SIDIUPG\" -o $@ $<

flash: $(PRJ).hex $(PRJ).upg $(PRJ).bin
	openocd $(INTERFACE) -f target/atsamv.cfg --command "adapter speed $(ADAPTER_KHZ); init; reset init; sleep 1; flash protect 0 0 last off; flash erase_sector 0 0 last; sleep 10; flash write_bank 0 firmware.bin 0; mww 0x400e0c04 0x5a00010b; resume; shutdown"

flash_sam: $(PRJ).hex
	Sam_I_Am -x flash_sam_i_am

# Convert ELF binary to bin file.
$(PRJ).bin: $(PRJ).elf
	$(CP) -O binary $< $@

# Convert ELF binary to Intel HEX file.
$(PRJ).hex: $(PRJ).elf
	$(CP) $(CPFLAGS) $< $@

# Link - this produces an ELF binary.
$(PRJ).elf: $(OBJ)
	$(LD) $(LFLAGS) -o $@ $+ $(LIBS)
	$(SIZE) -B $@

$(PRJ).upg: $(PRJ).bin $(MKUPG)
	./$(MKUPG) $< $@ $(TODAY)

%.o: %.c
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

%.d: ;

sections: $(PRJ).elf
	$(DUMP) --section-headers $<

release:
	make $(PRJ).hex $(PRJ).bin $(PRJ).upg
	cp $(PRJ).hex $(PRJ).bin $(PRJ).upg ../bin/firmware

-include $(DEP)
