PRJ = hidtest
SRC = hid_test.c usb/usb.c usb/usbdebug.c usb/hid.c usb/hidparser.c usb/hidquirks.c state.c utils.c

OBJ = $(SRC:.c=.o)
DEP = $(SRC:.c=.d)

DFLAGS = -DDEBUG_HID -DDEBUG_HIDP
DFLAGS += -Diprintf=printf -D_strnicmp=strncasecmp
DFLAGS += -DFF_LFN_BUF=255 -DSECTOR_BUFFER_SIZE=4096 -DFORCE_ARM="" -DRAMFUNC=""
CFLAGS  = $(DFLAGS) -Wall -Wno-pointer-sign -Wno-attributes -fsanitize=address -fno-omit-frame-pointer -I. -Iusb -Ihw/AT91SAM -g -O0

# Our target.
all: $(PRJ)

$(PRJ): $(OBJ)
	$(CC) -pg -fsanitize=address -o $@ $(OBJ)

clean:
	rm -f $(OBJ) $(PRJ) gmon.out
