PRJ = fattest
SRC = fat_test.c fat_compat.c diskio.c FatFs/ff.c FatFs/ffunicode.c

OBJ = $(SRC:.c=.o)
DEP = $(SRC:.c=.d)

DFLAGS  = -DFF_FS_TINY=1 -DFF_MAX_LFN=64 -DFF_LFN_BUF=64
DFLAGS += -DFAT_TEST -Diprintf=printf -D_strnicmp=strncasecmp
CFLAGS  = $(DFLAGS) -Wno-attributes -I. -Iusb -Ihw/AT91SAM -g -O0

# Our target.
all: $(PRJ)

$(PRJ): $(OBJ)
	$(CC) -pg -o $@ $(OBJ)

clean:
	rm -f $(OBJ) $(PRJ)
